### ISSUE TITLE
BLEU evaluation code is wrong

### ISSUE THREAD

**Issue by jind11** [lisjin/hct#1]
hi, thank you for sharing this source code. I found one bug in lines 25-28 in the score.py file (https://github.com/lisjin/hct/blob/a092d5f301234a4ca6511bd1c7f5f06bf3279e96/score.py#L25). Here to calculate the corpus_bleu score, reference and hypothesis sentences need to be as lists instead of strings. Please refer to the NLTK document for more details: https://www.nltk.org/_modules/nltk/translate/bleu_score.html. After this code correction, I have obtained new BLEU scores for the CANARD and MuDoCo datasets like the following:

CANARD: Avg. BLEU(n):   0.690 (1)       0.623 (2)       0.570 (3)       0.516 (4)
MuDoCo: Avg. BLEU(n):   0.928 (1)       0.901 (2)       0.874 (3)       0.845 (4)

Could you help check this code bug and make the corresponding correction in both this source code and paper? Thank you so much!

**Comment by lisjin** [comment]
Hi, thanks for bringing this to my attention. I have pushed the fix in bcd19ecfa30d049f1b409a427a009548e2fcd363. Let me know if this matches your fix. I will also make sure the final AAAI version will have the corrected BLEU scores.

**Comment by jind11** [comment]
Thank you for the quick reply! Look forward to your update on the paper.

**Comment by jind11** [comment]
May I know whether you have updated the BLEU scores in the AAAI paper: https://www.aaai.org/AAAI22Papers/AAAI-3890.JinL.pdf? Thank you so much!

**Comment by lisjin** [comment]
The final version has been submitted but the 2022 AAAI proceedings haven't been released yet. I think they'll eventually show up here: https://aaai.org/Library/AAAI/aaai-library.php

On May 17, 2022 7:38 PM, Di Jin ***@***.***> wrote:

May I know whether you have updated the BLEU scores in the AAAI paper: https://www.aaai.org/AAAI22Papers/AAAI-3890.JinL.pdf<https://urldefense.com/v3/__https://www.aaai.org/AAAI22Papers/AAAI-3890.JinL.pdf__;!!CGUSO5OYRnA7CQ!JLL7MsCpKzWd944UvbhRvOEF7NC0QhimCacDXJHcvzAnpiBYAaEOv_WZkXaV552I39w$>? Thank you so much!

**Comment by lisjin** [comment]
@jind11 FYI, there's now a preprint of the final version [here](https://arxiv.org/abs/2206.11218).

**Comment by jind11** [comment]
Thank you so much!
